module Cuintet.Memory where

import Clash.Prelude
import Cuintet.Eei

memory ::
  ( HiddenClockResetEnable dom
  , KnownNat dataWidth
  , KnownNat addrWidth
  ) =>
  -- | one-cycle-delayed memory, generated by `blockRam` family.
  ( Signal dom (Unsigned addrWidth) ->
    Signal dom (Maybe (Unsigned addrWidth, BitVector dataWidth)) ->
    Signal dom (BitVector dataWidth)
  ) ->
  Signal dom (MemBusReq dataWidth addrWidth) ->
  Signal dom (MemBusResp dataWidth)
memory ram req = MemBusResp True <$> rvalid <*> rdata
 where
  rvalid = register False (valid <$> req)
  rdata = ram (addr <$> req) (write <$> req)
  write MemBusReq{..}
    | valid && wen = Just (addr, wdata)
    | otherwise = Nothing
