module Cuintet.Memory where

import Clash.Prelude
import Cuintet.Eei

memory ::
  ( HiddenClockResetEnable dom
  , KnownNat dataWidth
  , KnownNat addrWidth
  ) =>
  -- | one-cycle-delayed memory, generated by `blockRam` family.
  ( Signal dom (Unsigned addrWidth) ->
    Signal dom (Maybe (Unsigned addrWidth, BitVector dataWidth)) ->
    Signal dom (BitVector dataWidth)
  ) ->
  Signal dom (MemBusReq dataWidth addrWidth) ->
  Signal dom (MemBusResp dataWidth)
memory ram req = MemBusResp True <$> rdata
 where
  write MemBusReq{..}
    | valid, Just wd <- wdata = Just (addr, wd)
    | otherwise = Nothing
  mkRdata valid v
    | valid = Just v
    | otherwise = Nothing

  r = ram ((.addr) <$> req) (write <$> req)
  -- The read data is valid one cycle after the request, matching the ram delay.
  rdata = mkRdata <$> register False ((.valid) <$> req) <*> r
