cabal-version: 3.8
name: cuintet
version: 0.1
synopsis: A RISC-V CPU written in Clash.
license: BSD-3-Clause
license-file: LICENSE
author: atree4728
maintainer: atree.public@gmail.com
build-type: Simple
extra-doc-files:
  README.md

common common-options
  default-language: GHC2024
  default-extensions:
    DefaultSignatures
    DeriveAnyClass
    DuplicateRecordFields
    NoFieldSelectors
    NoImplicitPrelude
    NoStarIsType
    OverloadedRecordDot
    PatternSynonyms
    QuasiQuotes
    RecordWildCards
    TemplateHaskell
    TypeFamilies
    UndecidableInstances
    ViewPatterns

  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints
    -Wunused-packages
    -haddock
    -fplugin
    GHC.TypeLits.Extra.Solver
    -fplugin
    GHC.TypeLits.Normalise
    -fplugin
    GHC.TypeLits.KnownNat.Solver
    -fexpose-all-unfoldings
    -fno-worker-wrapper
    -fno-unbox-small-strict-fields
    -fno-unbox-strict-fields

  build-depends:
    base,
    clash-prelude >=1.10.0 && <1.12,
    ghc-typelits-extra,
    ghc-typelits-knownnat,
    ghc-typelits-natnormalise,

library
  import: common-options
  hs-source-dirs: src
  -- cabal-gild: discover src
  exposed-modules:
    Cuintet
    Cuintet.BusArbiter
    Cuintet.Core
    Cuintet.CoreCtrl
    Cuintet.CsrUnit
    Cuintet.Debug
    Cuintet.Eei
    Cuintet.Fifo
    Cuintet.LoadStoreUnit
    Cuintet.Pipeline
    Cuintet.Ram
    Cuintet.RegFile
    Cuintet.Stage.Decode
    Cuintet.Stage.Execute
    Cuintet.Stage.Fetch
    Cuintet.Stage.MemAccess
    Cuintet.Stage.Writeback
    Cuintet.Util

common clash-exe
  default-language: GHC2024
  build-depends:
    base,
    clash-ghc,
    cuintet,

  if !os(windows)
    ghc-options: -dynamic

executable clash
  import: clash-exe
  main-is: bin/Clash.hs

executable clashi
  import: clash-exe
  main-is: bin/Clashi.hs

test-suite doctests
  type: exitcode-stdio-1.0
  default-language: GHC2024
  main-is: doctests.hs
  hs-source-dirs: tests
  ghc-options:
    -Wall
    -Wcompat
    -threaded

  build-depends:
    base,
    cuintet,
    doctest-parallel >=0.2 && <0.5,

test-suite unittests
  import: common-options
  type: exitcode-stdio-1.0
  main-is: unittests.hs
  hs-source-dirs: tests
  ghc-options: -threaded
  other-modules:
    Tests.Cuintet.Core
    Tests.Cuintet.RiscvTests
    Tests.Cuintet.Sim

  build-depends:
    bytestring,
    cuintet,
    file-embed >=0.0.15 && <0.1,
    filepath,
    tasty >=1.2 && <1.6,
    tasty-hunit,
