cabal-version: 3.8
name: cuintet
version: 0.1
synopsis: A RISC-V CPU written in Clash.
license: BSD-3-Clause
license-file: LICENSE
author: atree4728
maintainer: atree.public@gmail.com
build-type: Simple
extra-doc-files:
  README.md

common warnings
  default-language: GHC2024
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints
    -Wunused-packages

common clash
  import: warnings
  default-extensions:
    DefaultSignatures
    DeriveAnyClass
    DuplicateRecordFields
    NoFieldSelectors
    NoImplicitPrelude
    NoStarIsType
    OverloadedRecordDot
    PatternSynonyms
    QuasiQuotes
    RecordWildCards
    TemplateHaskell
    TypeFamilies
    UndecidableInstances
    ViewPatterns

  ghc-options:
    -fplugin=GHC.TypeLits.Extra.Solver
    -fplugin=GHC.TypeLits.KnownNat.Solver
    -fplugin=GHC.TypeLits.Normalise

  build-depends:
    base,
    clash-prelude >=1.10.1 && <1.12,
    ghc-typelits-extra,
    ghc-typelits-knownnat,
    ghc-typelits-natnormalise,

library
  import: clash
  hs-source-dirs: src
  ghc-options:
    -haddock
    -fexpose-all-unfoldings
    -fno-worker-wrapper
    -fno-unbox-small-strict-fields
    -fno-unbox-strict-fields

  -- cabal-gild: discover src
  exposed-modules:
    Cuintet
    Cuintet.Core
    Cuintet.CoreCtrl
    Cuintet.Debug.Image
    Cuintet.Debug.Konata
    Cuintet.Debug.Show
    Cuintet.Debug.Sim
    Cuintet.Debug.Spike
    Cuintet.Eei
    Cuintet.Forwarding
    Cuintet.Pipeline
    Cuintet.Stage.Commit
    Cuintet.Stage.Decode
    Cuintet.Stage.Execute
    Cuintet.Stage.Fetch
    Cuintet.Stage.RegRead
    Cuintet.Stage.Rename
    Cuintet.Stage.WriteBack
    Cuintet.Top.TangNano9k
    Cuintet.Top.Timing
    Cuintet.Unit.Btb
    Cuintet.Unit.BusArbiter
    Cuintet.Unit.Csr
    Cuintet.Unit.Fifo
    Cuintet.Unit.LoadStore
    Cuintet.Unit.MulDiv
    Cuintet.Unit.MulDiv.Div
    Cuintet.Unit.MulDiv.Mul
    Cuintet.Unit.MultiRam
    Cuintet.Unit.Ram
    Cuintet.Unit.RegFile
    Cuintet.Unit.Ring
    Cuintet.Unit.Rob
    Cuintet.Upto
    Cuintet.Util

  build-depends:
    attoparsec >=0.14 && <0.15,
    bytestring,
    process,
    temporary,

executable konata
  import: clash
  main-is: bin/Konata.hs
  build-depends: cuintet

executable tracediff
  import: clash
  main-is: bin/TraceDiff.hs
  build-depends: cuintet

common clash-exe
  default-language: GHC2024
  ghc-options: "-with-rtsopts=-K512M -H -I5 -T"
  build-depends:
    base,
    clash-ghc,
    cuintet,

  if !os(windows)
    ghc-options: -dynamic

executable clash
  import: clash-exe
  main-is: bin/Clash.hs

executable clashi
  import: clash-exe
  main-is: bin/Clashi.hs

test-suite doctests
  import: warnings
  type: exitcode-stdio-1.0
  main-is: doctests.hs
  hs-source-dirs: tests
  ghc-options:
    -threaded
    -Wno-unused-packages

  build-depends:
    base,
    cuintet,
    doctest-parallel >=0.2 && <0.5,

common programs
  import: clash
  hs-source-dirs: tests
  other-modules: Programs
  build-depends:
    bytestring,
    cuintet,
    file-embed >=0.0.15 && <0.1,
    filepath,

test-suite unittests
  import: programs
  type: exitcode-stdio-1.0
  main-is: unittests.hs
  ghc-options: -threaded
  other-modules:
    Tests.Cuintet.Core
    Tests.Cuintet.RiscvTests

  build-depends:
    tasty >=1.2 && <1.6,
    tasty-hunit,

benchmark bench
  import: programs
  type: exitcode-stdio-1.0
  main-is: bench.hs
